#! /usr/bin/env node

var MongoClient = require('mongodb').MongoClient;
var assert = require('assert');

var url = 'mongodb://localhost:27017/cljsketch';
MongoClient.connect(url, function(err, db) {

    db.collection("sketches").insertOne({
        name: 'foo',
        what: 'ho'
    });


    assert.equal(null, err);
    console.log("Connected correctly to server.");
    db.close();
});
